site_name: htmf - HTML in Python f-strings
site_url: https://jkmnt.github.io/htmf
nav:
 - Intro: index.md
 - Motivation: rant.md
 - Utilities: api.md
 - Linting: lint.md
 - Formatting: format.md
 - Highlighting: highlight.md
theme:
  name: material
  highlightjs: false
  features:
  #  - navigation.tabs
   - toc.integrate
  palette:
   primary: blue grey
repo_url: https://github.com/jkmnt/htmf
plugins: []
extra_css:
  - extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

